version: "3"
services:
  web:
    image: $CONTAINER_IMAGE
    deploy:
      labels:
      - "traefik.port=8080"
      - "traefik.backend=$STACK_NAME"
      - "traefik.frontend.rule=Host:$STACK_HOST"
      - "traefik.docker.network=traefik_net"
      replicas: 1
    networks:
    - traefik_net

networks:
    traefik_net:
      external: true
